[package]
name = "gravity-simulator"
authors = [
    "Avee121",
    "Michael de Silva <michael@cyberdynea.io>"
]
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
nalgebra = "0.33.2"
rand = "0.8.5"
rayon = "1.10.0"
rerun = "0.18.0"
